### ISSUE TITLE
9bit colours and L2 colour priority bit description omitted

### ISSUE THREAD

**Issue by ped7g** [tomaz/zx-next-dev-guide#2]
https://github.com/tomaz/zx-next-dev-guide/blob/bf731f585c380ac559b9d397bd0af45098b0ee27/zx-next-dev-guide.tex#L2177

https://github.com/tomaz/zx-next-dev-guide/blob/bf731f585c380ac559b9d397bd0af45098b0ee27/zx-next-dev-guide.tex#L2781

The whole Layer2 chapter skips 9bit colours (nextreg $44), and the extra priority bit for Layer2, while it seems the Layer2 is the only chapter trying to describe ZX Next palette features.

I find this omission somewhat unfortunate, as 332 colour space is limited in blues and grey shadows, while L2 priority bit is useful only in very rare use cases, but it would made the whole chapter more complete (seems quite complete and neat already).

**Comment by tomaz** [comment]
Palette now has its own chapter with explanation of 8-bit and 9-bit modes and extra Layer 2 priority bit . Also moved all palette registers to that chapter (and added missing ones so all of the following are included: `$40`-`$44` and `$4A`)

L2 chapter still mentions palette handling and references back to palette chapter. Deliberated on removing this, but, given that removing palette section resulted in half page empty that couldn't be filled nicely, decided to leave it in + add some additional text to _Drawing_ and _Effects_ sections. Besides L2 has extra priority functionality which deserves mentioning again.

In similar way, I thought of adding some mention to other "affected" chapters as well (ULA, Tilemap and Sprites), but decided to keep it as is for the moment being (apart from ULA where I added a sentence noting default colours can be changed on Next). Given Palette chapter is positioned before all of them + added all register as references back to it, so I concluded it should be enough...
