### ISSUE TITLE
LDDX is documented incorrectly

### ISSUE THREAD

**Issue by taylorza** [tomaz/zx-next-dev-guide#21]
Chapter 4.15 : LDDX documented as `BC = BC + 1`, this should be `BC = BC - 1`
Same on page 171 in Chapter 5

**Comment by tomaz** [comment]
Thanks, will fix! It's likely wrong in all places where `LDDX` is listed since all instruction "components" are implemented as reusable macros

**Comment by tomaz** [comment]
Finally fixed 😅

Thanks again for mentioning. Also again, big thanks for your PR too! Definitely let me know if you spot anything else - just open an issue, or if you feel for it, create PR, both will go big ways into making the book more accurate. Attaching updated PDF. I'll wait a bit in case other issues are reported then probably create another pre-release here.

[zx-next-dev-guide.pdf](https://github.com/tomaz/zx-next-dev-guide/files/8013334/zx-next-dev-guide.pdf)

**Comment by taylorza** [comment]
Hi,

You are welcome and thank you for putting this together it is an awesome resource. It is much easier to get started with than anything else I have come across.

Best Regards,
Chris
