### ISSUE TITLE
Incorrect sprite attribute numbers

### ISSUE THREAD

**Issue by taylorza** [tomaz/zx-next-dev-guide#25]
The attribute numbers are incorrect for the 2nd to 4th attributes
https://github.com/tomaz/zx-next-dev-guide/blob/e485a9569be8c08fcbff52f6d7962c6c0e9670f2/chapter-next-sprites.tex#L326

**Comment by tomaz** [comment]
Thanks, the power of copy/paste at its "best" 😅 Fixed 👍
