### ISSUE TITLE
DMA - Base Register Byte

### ISSUE THREAD

**Issue by taylorza** [tomaz/zx-next-dev-guide#27]
https://github.com/tomaz/zx-next-dev-guide/blob/b724fbf9d5acae4cbb5ee1159b4f7f85a0923644/chapter-next-dma.tex#L870

The above sentence ends abruptly with "... owning the.", this should probably be "... owning the bus"

**Comment by tomaz** [comment]
Thanks! That's likely copy/paste issue. Though I can't exclude my brain excitingly jumping to next section while leaving my hands to wrap up existing one by themselves 😇

**Comment by tomaz** [comment]
Finally got to fixing this, I have couple more things to do, then will prepare a refreshed release. Thanks again for reporting!
