### ISSUE TITLE
MMU0+MMU1 ROM  paging

### ISSUE THREAD

**Issue by ped7g** [tomaz/zx-next-dev-guide#3]
https://github.com/tomaz/zx-next-dev-guide/blob/bf731f585c380ac559b9d397bd0af45098b0ee27/zx-next-dev-guide.tex#L1716

This chapter doesn't mention MMU0 and MMU1 ROM paging by writing $FF into both registers. May be nice to add it in case somebody experiments with paging RAM into bottom 16ki region, and then having no idea how to get back to ROM mapping?

**Comment by tomaz** [comment]
Thanks for mentioning, added this info to the bottom of MMU section:

> Note: MMU0 and MMU1 have extra functionality: ROM can be automatically paged in if otherwise nonexistent 8K page $FF is written.  Low or high 8K ROM bank is automatically determined based on which 8K slot is used.  This may be useful if temporarily paging RAM into the bottom16K region and then wanting to restore back to ROM.
